[package]
name = "auto-scunet"
version = "0.1.0"
edition = "2021"
authors = ["East Monster <east_monster@126.com>"]

[dependencies]
anyhow = "1"
eframe = { version = "0.27.0", default-features = false, features = ["glow"] }
egui = "0.27.0"
reqwest = { version = "0.12", features = ["json", "blocking"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
toml = "0.8"
serde = "1"
serde_derive = "1"
win-toast-notify = "0.1.3"

[profile.release]
strip = true
opt-level = "z"
